# Generated by Django 5.0.3 on 2024-05-09 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEmotion',
            fields=[
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.diary')),
                ('anger', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anxiety', models.FloatField()),
                ('hurt', models.FloatField()),
                ('panic', models.FloatField()),
                ('happyness', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='emotion',
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['writer'], name='myapp_diary_writer__0cae29_idx'),
        ),
    ]
