# Generated by Django 5.0.3 on 2024-05-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diaryemotion_remove_diary_emotion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryemotion',
            old_name='happyness',
            new_name='happiness',
        ),
    ]
